### ISSUE TITLE
Is there any tool for computing the cotangent weight matrix and local area from .ply data as mentioned in LSCNN paper?

### ISSUE THREAD

**Issue by wangg12** [jonathanmasci/ShapeNet#4]
I wonder if there is any tool for computing the cotangent matrix and local area from .ply data. Or could you share your code for computing those stuffs? 
Thanks @jonathanmasci

**Comment by jonathanmasci** [comment]
Hi @wangg12 ,
we're working on a python implementation to be integrated in the pre-processing tools.
